# 自动为每一篇文章生成封面
article:
  auto_cover: true
  # 相关文章推荐功能 npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
  # 分享至
  share: [wechat]
#  type: tech story 有两种风格可选，tech: 默认技术类文章, story: 图文类文章，文字和段落间增距大
# 设置鼠标指上 subtitle 后翻转另一行字（您可以将鼠标移至左上角的Stellar查看效果）
logo:
  subtitle: 'JTの博客 | 修身;齐家;治国;平天下'
# 默认生成 Open Graph 标签
# Open Graph (OG) 标签是网页上的一组特定的meta标签，用于控制当页面被分享到社交媒体平台（如Facebook、LinkedIn、Twitter等）时，显示的预览信息
open_graph:
  enable: true
  twitter_id: # for open_graph meta
# 侧边栏主功能导航菜单
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    # id: 页面中高亮的 menu_id
    # theme: 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
    # icon: 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
    # title: 标题
    # url: 点击跳转到哪，支持相对路径和绝对路径
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/
# 评论插件安装
comments:
  service: beaudar
  beaudar:
    repo: JiangTaot/blog-comments
