article:
  auto_cover: true # 自动为每一篇文章生成封面
  related_posts: # 相关文章推荐功能 npm i hexo-related-popular-posts
    enable: true
    title: 您可能感兴趣的文章
  license: '本文由{author.name}编写,遵循 CC BY-NC-SA 4.0 许可协议.转载请保留原文链接.'
#  share: [wechat] # 分享至
#  type: tech # story 有两种风格可选，tech: 默认技术类文章, story: 图文类文章，文字和段落间增距大

logo:
  subtitle: 'JTの博客 | 修身;齐家;治国;平天下' # 设置鼠标指上 subtitle 后翻转另一行字（您可以将鼠标移至左上角的Stellar查看效果）

open_graph:  # 标签  Open Graph (OG) 标签是网页上的一组特定的meta标签，用于控制当页面被分享到社交媒体平台（如Facebook、LinkedIn、Twitter等）时，显示的预览信息
  enable: true # 默认生成 Open Graph
  twitter_id: # for open_graph meta

menubar: # 侧边栏主功能导航菜单
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post                              # id: 页面中高亮的 menu_id
      theme: '#1BCDFC'                      # theme: 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone    # icon: 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 博客                            # title: 标题
      url: /                                # url: 点击跳转到哪，支持相对路径和绝对路径
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/
    - id: friends
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

comments: # 评论插件安装
  service: beaudar
  beaudar:
    repo: JiangTaot/blog-comments

author: JT

site_tree:
  friends:
    base_dir: friends
